descriptor_extension: yml
package: {description: Some description about this sample, maintainer: 'Name, Company,
    Contact', name: vepc_scaled_mgmt, vendor: eu.sonata-nfv.package, version: '0.1'}
version: '0.5'
